- name: Roboshop frontend
  hosts: all
  become: true
  tasks: 
    - name: Installing Nginx
      ansible.builtin.yum:
        name: nginx
        state: installed


    - name: Copying the config files
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Removing files
      ansible.builtin.file:
        state: absent 
        path: /usr/share/nginx/html

    - name: Creating dir
      ansible.builtin.file:
        state: directory
        path: /usr/share/nginx/html

    - name: Download 
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip 
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Start Nginx
      ansible.builtin.systemd:
         name: nginx
         state: restarted
         enabled: yes


